# -*- coding: utf-8 -*-
"""data_analytics_practise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1neFlML2iZSBSqyt1tJFHCEy4VoW_TgPi
"""

import numpy as np
import pandas as pd

train = pd.read_csv('train.csv',  index_col='id')
train.head(5)

train.nunique()

dups = train.duplicated()
print(dups.any())

# import seaborn as sns
# import matplotlib.pyplot as plt

# sns.pairplot(train)
# plt.show()

# Select numerical columns
num_cols = train.select_dtypes(include="number").columns
num_cols

# Calculate Q1 and Q3
Q1 = train[num_cols].quantile(0.25)
Q3 = train[num_cols].quantile(0.75)

print(Q1, Q3)

# Calculate IQR
IQR = Q3 - Q1

# Define bounds
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

# Keep rows where ALL numerical columns are within bounds
train_clean = train[
    ~((train[num_cols] < lower) | (train[num_cols] > upper)).any(axis=1)
].copy()

print("Before:", len(train))
print("After :", len(train_clean))
print("Removed:", len(train) - len(train_clean))

train_clean.isnull().sum()

stats = pd.DataFrame({
    "mean": train_clean.mean(numeric_only=True),
    "median": train_clean.median(numeric_only=True)
})

print(stats)

from sklearn.impute import SimpleImputer

mean_imputer = SimpleImputer(strategy="mean")
train_clean[num_cols] = mean_imputer.fit_transform(train_clean[num_cols])

train_clean.isnull().sum()

cat_cols = ["gender", "stress_level", "academic_work_impact"]

# Mode
mode_imputer = SimpleImputer(strategy="most_frequent")
train_clean[cat_cols] = mode_imputer.fit_transform(train_clean[cat_cols])

train_clean.isnull().sum()

correlation = train_clean.corr(numeric_only=True)["addicted_label"].sort_values(
    ascending=False
)

print(correlation)

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
train_clean[num_cols] = scaler.fit_transform(train_clean[num_cols])

train_clean

from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False, drop="first")
encoded_cols = pd.DataFrame(
    encoder.fit_transform(train_clean[cat_cols]),
    columns=encoder.get_feature_names_out(cat_cols),
    index=train_clean.index,
)

encoded_cols
train_clean = pd.concat([train_clean, encoded_cols], axis=1)
train_clean.drop(columns=cat_cols, inplace=True)

train_clean.head(5)

Y = train_clean["addicted_label"]
X = train_clean.drop(columns=["addicted_label"])

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42
)

from sklearn.linear_model import LogisticRegression

reggressor = LogisticRegression()
reggressor.fit(X_train, y_train)

predictions = reggressor.predict(X_test)

from sklearn.metrics import accuracy_score

accuracy_score(y_test, predictions)