# -*- coding: utf-8 -*-
"""Data_Visualization_Practise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CyLilxABeNAIwtmk79CtbkdcKOCDSlPX
"""

import matplotlib.pyplot as plt
import numpy as np

normal_data = np.random.normal(loc=0, scale=1, size=100)
normal_data

plt.hist(normal_data)
plt.xlabel("Random Data")
plt.ylabel("Frequencies in each bin")
plt.title("Histogram of Random Data")
plt.show()

import seaborn as sns

sns.histplot(normal_data, kde=True)
plt.xlabel("Random Data")
plt.ylabel("Frequencies in each bin")
plt.title("Histogram of Random Data")
plt.show()

# Box Plot

plt.boxplot(normal_data)
plt.xlabel("Random Data")
plt.ylabel("Frequencies in each bin")
plt.title("Histogram of Random Data")
plt.show()

sns.violinplot(normal_data)
plt.xlabel("Random Data")
plt.ylabel("Frequencies in each bin")
plt.title("Histogram of Random Data")
plt.show()

sns.stripplot(normal_data)
plt.xlabel("Random Data")
plt.ylabel("Frequencies in each bin")
plt.title("Histogram of Random Data")
plt.show()

sns.swarmplot(normal_data)
plt.xlabel("Random Data")
plt.ylabel("Frequencies in each bin")
plt.title("Histogram of Random Data")
plt.show()

import pandas as pd
df = pd.DataFrame({
    "salary": [
        30000, 32000, 35000, 37000, 40000,
        42000, 45000, 48000, 50000, 52000,
        55000, 60000, 65000, 70000, 150000
    ]
})

sns.histplot(
    data=df,
    x="salary",
    kde=True
)

plt.title("Salary Distribution")
plt.show()

sns.boxplot(
    data=df,
    x="salary"
)

plt.show()

sns.ecdfplot(
    data=df,
    x="salary"
)

plt.show()

departments = ["CSE", "AI", "ECE", "ME"]
students = [100, 80, 60, 40]

plt.bar(departments, students)

plt.xlabel("Department")
plt.ylabel("Number of Students")
plt.title("Students by Department")

plt.show()

departments = ["CSE", "AI", "ECE"]

male = [60, 45, 40]
female = [40, 35, 20]

x = np.arange(len(departments))

width = 0.35

plt.bar(x - width/2, male, width, label="Male")
plt.bar(x + width/2, female, width, label="Female")

plt.xticks(x, departments)
plt.ylabel("Students")
plt.xlabel("Department")
plt.title("Students by Department and Gender")
plt.legend()

plt.show()

categories = ["Electronics", "Clothing", "Food"]
sales = [50, 30, 20]

plt.pie(
    sales,
    labels=categories,
    autopct="%1.1f%%"
)

plt.title("Sales Distribution")

plt.show()

plt.pie(
    sales,
    labels=categories,
    autopct="%1.1f%%",
    wedgeprops={"width": 0.4}
)

plt.show()

import matplotlib.pyplot as plt
models = ["A", "B", "C"]
accuracy = [85, 88, 90]
errors = [2, 1.5, 1]

plt.errorbar(
    models,
    accuracy,
    yerr=errors,
    fmt="o"
)

plt.ylabel("Accuracy (%)")
plt.title("Model Accuracy with Error Bars")

plt.show()

import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5]
y = [2, 4, 6, 8, 10]
fig , ax = plt.subplots()
ax.plot(x,y)
plt.xlim(0,10)
plt.ylim(0,10)
plt.grid(True)
plt.show()

# Multiple Lines
months = [1,2,3,4,5]
sales_a = [10,20,30,40,50]
sales_b = [15,25,35,45,55]
plt.plot(months,sales_a, label="A")
plt.plot(months,sales_b, label="B")
plt.legend()
plt.show()

months = [1,2,3,4,5]
sales = [100,150,180,250,300]
plt.figure(figsize=(10,5))
plt.plot(
 months,
 sales,
 color='blue',
 marker='o',
 linewidth=3,
 label='Sales'
)
plt.title("Monthly Sales Analysis")
plt.xlabel("Month")
plt.ylabel("Revenue")
plt.grid(True)
plt.legend()
plt.show()

plt.savefig("sales.png")

