# -*- coding: utf-8 -*-
"""Numpy_for_Practise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11_Snp5IIxaWTJdLdjeQMHLG8Mk9ttCGN
"""

import numpy as np

arr = np.arange(100)

print(arr)

#vectorized operations

n_arr = arr * 2
print(n_arr)

# Creation of array

arr1 = np.array([[1,2],[3,2]], dtype=int, ndmin=3)
print(arr1.shape, arr1.dtype, arr1.ndim, arr1.size, arr1.itemsize, arr1.nbytes, arr1.T)

arr1.flat

np.zeros((3,2))

np.eye(3)

a = np.linspace(1,10,3)

a.dtype

b = a.astype('float32')
b.dtype

a = np.eye(5)
a

print(a[0:2,0:2]) # start : stop : step

a[::2, ::2]

# fancy indexing uses list indices to get the elements

a[[0,2,3],[0,3,4]]

# boolean indexing or masking

a[a>0]

# np.where() — Conditional Selection and Replacement
# One of the most-used NumPy functions in data pipelines. Can act as a vectorized if-else.

np.where(a>0,a,3) # return indices of the elements and can be use to replace the values

a = np.array([10, -5, 20, -3, 15,8])
np.where(a > 0, a, 0) # [10 0 20 0 15] — replace negatives with 0

a.reshape(2,3)

f = a.flatten()
f

rv = a.ravel()
rv

a

a.shape

b = np.expand_dims(a,axis=0)
b.shape

a.shape

c = np.expand_dims(a,axis=1)
c.shape

a[np.newaxis, :] # same as axis=0
a[:, np.newaxis] # same as axis=1

np.squeeze(a) # shape: (3,)
a.shape

# 2.3 Broadcasting — The Most Important Concept
# Broadcasting is NumPy's mechanism for performing operations on arrays of different shapes without
# explicitly replicating data. It is memory-efficient and is used everywhere in ML.

a = np.array([1,2,3])
b = a + 10
c = a*2
d = a**2
print(a,b,c,d)

e = a + d
print(e)

# reproducibility

np.random.seed(42)
a = np.random.rand(5)
a

uni = np.random.uniform(1,10,5)
uni

normal = np.random.normal(1,20,10)
normal

a = np.random.rand(2,3)
b = np.random.rand(3,2)

print(a,b)

c = a @ b
c

a = np.random.rand(2,2)
delta = np.linalg.det(a)
delta

inv_a = np.linalg.inv(a)
inv_a

I = a @ inv_a
I

A = np.array([[4,2],[1,3]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues, eigenvectors)

A = np.random.randn(5, 3)
U, s, Vt = np.linalg.svd(A, full_matrices=False)
print(U, s, Vt)

