# -*- coding: utf-8 -*-
"""Practise_Pytorch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Z5VGLm46IkqY14JPTd2DGSp7X9LC131
"""

from os import XATTR_SIZE_MAX
import torch
from torch import nn
from torch.utils.data import DataLoader, Dataset
import numpy as np



class MyDataset(Dataset):
  def __init__(self):
    self.x = np.random.normal(loc=0.0, scale=1.0, size=100)
    self.y = np.arange(0,100)

  def __len__(self):
    return len(self.x)


  def __getitem__(self, ind):
    return self.x[ind], self.y[ind]


dataset = MyDataset()
print(dataset[2])

batch_size = 4
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

for x , y in dataloader:
  print("Input:",x,"Output:",y)

class MyModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.flatten = nn.Flatten()
    self.classifier = nn.Sequential(
        nn.Linear(100,512),
        nn.ReLU(),
        nn.Linear(512,100)
    )

  def forward(self,x):
    x = self.flatten(x)
    logits = self.classifier(x)
    return logits


model = MyModel()

print(model)

# Optimizing the Model Parameters
print(model.parameters())

loss_fnc = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.05)

def train(model, dataloader, optimizer, loss_fnc):
  size = len(dataloader.dataset)
  model.train()
  for x, y in dataloader:
    preds = model(x)
    loss = loss_fnc(preds,y)

    # Back propagation
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

    print(loss.item())

def test(dataloader, model, loss_fn):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    model.eval()
    test_loss, correct = 0, 0
    with torch.no_grad():
        for X, y in dataloader:
            pred = model(X)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()
    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")

epochs = 5
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train(model, dataloader,optimizer, loss_fnc)
    # test(test_dataloader, model, loss_fn)
print("Done!")

