# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

from sklearn.datasets import load_iris
iris = load_iris()

x = iris.data
y = iris.target

# print(x.shape, y.shape)
print(x)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x)
x_scaled = scaler.transform(x)
print(x_scaled)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y , test_size=0.2, random_state=42)
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score


# Create Model
model = RandomForestClassifier(
 n_estimators=100,
 random_state=42
)
# Train
model.fit(x_train, y_train)
# Predict
predictions = model.predict(x_test)
# Evaluate
accuracy = accuracy_score(y_test, predictions)
print(f"Accuracy: {accuracy:.4f}")

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')

x_filled = imputer.fit_transform(x)
print(x_filled)

from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(
 handle_unknown="ignore"
)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(x)

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

# Scikit-Learn Pipeline
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

pipeline = Pipeline([
 ("imputer", SimpleImputer(strategy="mean")),
 ("scaler", StandardScaler()),
 ("model", LogisticRegression())
])

pipeline.fit(x_train, y_train)

predictions = pipeline.predict(x_test)

# ColumnTransformer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
numeric_features = [
 "age",
 "salary"
]
categorical_features = [
 "city"
]
preprocessor = ColumnTransformer(
 transformers=[
 (
 "num",
 StandardScaler(),
 numeric_features
 ),
 (
 "cat",
 OneHotEncoder(
 handle_unknown="ignore"
 ),
 categorical_features
 )
 ]
)

from sklearn.ensemble import RandomForestClassifier
pipeline = Pipeline([
 ("preprocessor", preprocessor),
 (
 "model",
 RandomForestClassifier(
 random_state=42
 )
 )
])

# Using GridSearchCV
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(
 random_state=42
)
param_grid = {
 "max_depth": [5, 10, 15],
 "n_estimators": [100, 200]
}
grid_search = GridSearchCV(
 estimator=model,
 param_grid=param_grid,
 cv=5,
 scoring="accuracy",
 n_jobs=-1
)
grid_search.fit(x_train, y_train)

grid_search.best_params_

grid_search.best_score_

# Randomized Search
from sklearn.model_selection import RandomizedSearchCV

param_dist = {
 "max_depth": [5,10,15,20,25],
 "n_estimators": [100,200,300,400,500]
}

random_search = RandomizedSearchCV(
 estimator=model,
 param_distributions=param_dist,
 n_iter=1,
 cv=5,
 random_state=42,
 n_jobs=-1
)

# SelectKBest
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
selector = SelectKBest(
 score_func=f_classif,
 k=5
)
X_selected = selector.fit_transform(x, y)
print(X_selected.shape)

selector.scores_

# Recursive Feature Elimination (RFE)
from sklearn.feature_selection import RFE

rfe = RFE(
 estimator=LogisticRegression(),
 n_features_to_select=5
)

# saving model
import joblib
joblib.dump(
 pipeline,
 "model.pkl"
)

model = joblib.load(
 "model.pkl"
)

